version: 2.1
jobs:
  build:
    docker:
        - image: circleci/node:12 # the primary container, where your job's commands are run
    steps:
      - run: echo "hello world" # run the `echo` command
      - run: npm -v
