version: 2
jobs:
  build:
    docker:
      - image: circleci/node:1
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ea:7c:99:e1:85:b0:1f:bc:59:67:78:40:de:99:6f:11"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
